# Generated by Django 5.1.7 on 2025-04-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='thumbnails/'),
        ),
    ]
