# Generated by Django 5.1.6 on 2025-03-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='roles',
            field=models.ManyToManyField(through='users.UserRole', to='users.role'),
        ),
    ]
